### ISSUE TITLE
ligatures are missing

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hoodie-css#2]
@verpixelt could you add more information how you fixed the issue last time?
I'd love to end the migration by this week.

Thanks!

**Comment by verpixelt** [comment]
I got the font files directly from Font Squirrel and encoded them with their tool (http://www.fontsquirrel.com/tools/webfont-generator).

**Comment by zoepage** [comment]
Are the files uploaded somewhere?
(you said, the ones in the hood.ie repo are outdated too?)

**Comment by verpixelt** [comment]
Here you go: https://github.com/hoodiehq/hoodie-css/pull/3

**Comment by zoepage** [comment]
The fonts are back up and the issues was fixed with this commit: https://github.com/hoodiehq/hoodie-css/commit/e86bf373ecee912725699d83d44fb490ef17c317

The webfont generator had issues with more than one file during generation and canceled the download after generation. Still not sure why. This is why I'd suggest to generate just one file after another.

Download the font from fontsquirrel. 
Then generate the web font with http://www.fontsquirrel.com/tools/webfont-generator

Select the expert mode. 

![bildschirmfoto 2015-08-20 um 10 26 49](https://cloud.githubusercontent.com/assets/562354/9378969/077befe8-4726-11e5-8aca-98330521b5d4.png)

![bildschirmfoto 2015-08-20 um 10 26 57](https://cloud.githubusercontent.com/assets/562354/9378968/07760ae2-4726-11e5-9939-5c4a61d0b867.png)
