### ISSUE TITLE
Feature: Security vulnerability check

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/hoodie-css#30]
We should integrate [requiresafe](https://www.npmjs.com/package/requiresafe) into our builds to ensure that we remain knowledgeable of any security vulnerabilities that occur in any of our dependencies.

**Comment by varjmes** [comment]
Seconded!

**Comment by verpixelt** [comment]
Is that really necessary? I'm all in for security but it seems a bit over the top for me for a mostly static website. Can someone enlighten me?

**Comment by lewiscowper** [comment]
It's the tooling around the website I'm most worried about. If git clone +
npm installing the things we use leaves someone open to a security hole,
then I'd rather use an automatic tool to check that, over messing up
someone's computer.

See also the number of people who use sudo to npm install.

**Comment by verpixelt** [comment]
If we can automate that within a process so the users do not have to care, grant. Otherwise I'm worried this makes our setup even more complex. It is already way too complex for ppl to get started.
