### ISSUE TITLE
Image missing at readme?

### ISSUE THREAD

**Issue by katopz** [hoodiehq/hoodie-css#4]
![screen shot 2558-08-06 at 14 58 42](https://cloud.githubusercontent.com/assets/97060/9106596/ad386866-3c4b-11e5-8fec-4c03696aa428.png)

Cheers

**Comment by verpixelt** [comment]
Hey @katopz thanks for the heads up. We're aware of it and a fix is on its way ;)

**Comment by zoepage** [comment]
Actually I'm now on it! :D 

Thanks @katopz!

**Comment by zoepage** [comment]
And done here: http://hoodiehq.github.io/hoodie-css/colour-fonts.html
