### ISSUE TITLE
Underlines look weird on Chrome + FF

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/hoodie-css#42]
![hoodie-underline-legibility](https://cloud.githubusercontent.com/assets/593574/11499281/3f448a20-9825-11e5-9eb3-92ceb2b0557c.png)

Looks like reoccurence of https://github.com/hoodiehq/hood.ie/issues/100 which should have been fixed with: https://github.com/hoodiehq/hood.ie/commit/e7383714dc8f7b8645f3259a25c2812a9f8f0105

Will look into it

**Comment by NickColley** [comment]
Normal underlines look decent to me, Reimplementing underlines seems like you'll be chasing your own tail to get right, not sure it's worth it?

**Comment by lewiscowper** [comment]
copy pasting from Slack:

(me)
yep, I don’t know how we’re going to fix it, it’s caused because we’re reimplementing underlines for reasons that either did work and are now broken, or never worked because they were unfinished. I don’t know. I remember discussing it with @espy in here, and that was the explanation.

So I don’t know how to fix the reimplementation of underlines, so a decision has to be made by someone who is vaguely in charge of design and stuff as to whether we scrap re-implementing underlines and switch to a regular underline, or what.

**Comment by verpixelt** [comment]
I've double checked them again and they work. Reimplementing them at the time had seemed to be a good idea, not anymore so later.
